CREATE DATABASE chat;
CREATE USER chat_user WITH SUPERUSER LOGIN PASSWORD 'test123';
\connect chat;
CREATE TABLE history (id serial PRIMARY KEY, username VARCHAR (255) DEFAULT NULL, message TEXT DEFAULT NULL, date_created DATE NOT NULL DEFAULT CURRENT_DATE );
